require:
  - rubocop-rake
  - rubocop-minitest

AllCops:
  TargetRubyVersion: 2.5
  NewCops: enable

Naming/MethodParameterName:
  Enabled: false

Metrics/MethodLength:
  Enabled: false

Metrics/AbcSize:
  Enabled: false

Style/Documentation:
  Enabled: false
