require:
  - rubocop-rake
  - rubocop-minitest

AllCops:
  TargetRubyVersion: 3.0
  NewCops: enable

Metrics/MethodLength:
  Enabled: false

Metrics/AbcSize:
  Enabled: false

Style/Documentation:
  Enabled: false
