name: Install Tests
on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        ruby-version:
          - "3.0"
          - "3.1"
          - "3.2"
          - "3.3"

    steps:
      - uses: actions/checkout@v4
      - name: Set up Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: ${{ matrix.ruby-version }}
          bundler-cache: true # runs 'bundle install' and caches installed gems automatically
      - name: "Install"
        run: bundle exec rake install
      - name: "Command: Version"
        run: bundle exec stylegen version
      - name: "Command: Init"
        run: bundle exec stylegen init
      - name: "Command: Build"
        run: bundle exec stylegen build
